aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  dynamodb:
    region: ${DYNAMO_REGION}
    access-key: ${DYNAMO_ACCESS}
    secret-key: ${DYNAMO_SECRET}
  sqs:
    enabled: true
    stack:
      auto: false
    region:
      static: ${SQS_REGION}

server:
  port: 8080

logging:
  level:
    root: info

jwt:
  secret:
    key: ${JWT_SECRET}
    expiration:
      access-token: ${ACCESS_EXPIRATION}
      refresh-token: ${REFRESH_EXPIRATION}

vworld:
  api:
    key: ${VWORLD_KEY}

its:
  api:
    key: ${ITS_KEY}