spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true

aws:
  dynamodb:
    region: ${DYNAMO_REGION}
  sqs:
    enabled: true
    stack:
      auto: false
    region:
      static: ${SQS_REGION}
    queues:
      fcm-token-queue: ${SQS_NAME}

server:
  port: 8080

logging:
  level:
    root: info

jwt:
  secret:
    key: ${JWT_SECRET}
    expiration:
      access-token: ${ACCESS_EXPIRATION}
      refresh-token: ${REFRESH_EXPIRATION}

vworld:
  api:
    key: ${VWORLD_KEY}

its:
  api:
    key: ${ITS_KEY}
